// user actions
export const GET_USERS = "GET_USERS";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const EDIT_BIO = "EDIT_BIO";
export const CREATE_CONNECTION = "CREATE_CONNECTIOn";
export const GET_FAVORITES = "GET_FAVORITES";
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_OVERLAP_SCHEDULES = "GET_OVERLAP_SCHEDULES";
export const CREATE_INVITE = "CREATE_INVITE";
export const GET_CONFIRMED_SESSIONS = "GET_CONFIRMED_SESSIONS";

export const GET_SCHEDULES = "GET_SCHEDULES";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
